// Generated by typings
// Source: ../typings/react-router-active-component/react-router-active-component.d.ts
// Type definitions for react-router-active-component v4.0.0-rc.0
// Project: https://github.com/insin/react-router-active-component
// Definitions by: Donovan Adams <https://github.com/hydrotik>
// Definitions: https://github.com/borisyankov/DefinitelyTyped



declare module "react-router-active-component" {
    export default function activeComponent(Component: any, options?: any): any;
}