// Generated by typings
// Source: ../Code/typings/raster-tile-style/raster-tile-style.d.ts
declare module __RasterTileStyle {
    export function rasterTileStyle(tiles: any, tileSize: number): any;
}

declare module "raster-tile-style" {
    export = __RasterTileStyle;
}