// Generated by typings
// Source: ../Code/typings/react-d3-basic/react-d3-basic.d.ts
declare module __ReactD3Basic {

    export interface IBasicProps {
        title?: string;

        width?: number;

        height?: number;

        margins?: any;

        data?: any;

        chartSeries?: any;

        x?: any;

        className?: any;
    }

    export class LineChart extends React.Component<IBasicProps, {}>{ }
    
}

declare module "react-d3-basic" {
    export = __ReactD3Basic;
}