// Generated by typings
// Source: ../Code/typings/react-chartjs/react-chartjs.d.ts
declare module __ReactChartJS {

    export interface IChartOptions {

        ///Boolean - Whether grid lines are shown across the chart
        scaleShowGridLines?: string;

        //String - Colour of the grid lines
        scaleGridLineColor?: string;

        //Number - Width of the grid lines
        scaleGridLineWidth?: number;

        //Boolean - Whether to show horizontal lines (except X axis)
        scaleShowHorizontalLines?: boolean;

        //Boolean - Whether to show vertical lines (except Y axis)
        scaleShowVerticalLines?: boolean;

        //Boolean - Whether the line is curved between points
        bezierCurve?: boolean;

        //Number - Tension of the bezier curve between points
        bezierCurveTension?: number;

        //Boolean - Whether to show a dot for each point
        pointDot?: boolean;

        //Number - Radius of each point dot in pixels
        pointDotRadius?: number;

        //Number - Pixel width of point dot stroke
        pointDotStrokeWidth?: number;

        //Number - amount extra to add to the radius to cater for hit detection outside the drawn point
        pointHitDetectionRadius?: number;

        //Boolean - Whether to show a stroke for datasets
        datasetStroke?: boolean;

        //Number - Pixel width of dataset stroke
        datasetStrokeWidth?: number;

        //Boolean - Whether to fill the dataset with a colour
        datasetFill?: boolean;

        //String - A legend template
        legendTemplate?: string;
    }


    export interface ILineProps {
        data: any;

        options?: IChartOptions;
    }

    export class Line extends React.Component<ILineProps, {}>{ }

    export interface IBarProps {
        data: any;

        options?: IChartOptions;
    }

    export class Bar extends React.Component<IBarProps, {}>{ }

    export interface IRadarProps {
        data: any;

        options?: IChartOptions;
    }

    export class Radar extends React.Component<IRadarProps, {}>{ }

    export interface IPolarAreaProps {
        data: any;

        options?: IChartOptions;
    }

    export class PolarArea extends React.Component<IPolarAreaProps, {}>{ }

    export interface IPieProps {
        data: any;

        options?: IChartOptions;
    }

    export class Pie extends React.Component<IPieProps, {}>{ }

    export interface IDoughnutProps {
        data: any;

        options?: IChartOptions;
    }

    export class Doughnut extends React.Component<IDoughnutProps, {}>{ }

}

declare module "react-chartjs" {
    export = __ReactChartJS;
}