// Generated by typings
// Source: https://raw.githubusercontent.com/dhsaks/typescript-definitions/66fdaab8fd24902429204d7c269387ca011c1428/raster-tile-style/index.d.ts
declare module "raster-tile-style" {
    export function rasterTileStyle(tiles: any, tileSize?: number): any;
}