// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/fc341765ebbb04b7109981a25dced01f488f4d94/redux-logger/redux-logger.d.ts
// Type definitions for redux-logger v2.0.0
// Project: https://github.com/fcomb/redux-logger
// Definitions by: Alexander Rusakov <https://github.com/arusakov/>
// Definitions: https://github.com/borisyankov/DefinitelyTyped


declare module 'redux-logger' {

  interface ReduxLoggerOptions {
    actionTransformer?: (action: any) => any;
    collapsed?: boolean;
    duration?: boolean;
    level?: string;
    logger?: any;
    predicate?: (getState: Function, action: any) => boolean;
    timestamp?: boolean;
    transformer?: (state:any) => any;
  }

  export default function createLogger(options?: ReduxLoggerOptions): Redux.Middleware;
}