// Generated by typings
// Source: https://raw.githubusercontent.com/dhsaks/typescript-definitions/66fdaab8fd24902429204d7c269387ca011c1428/react-d3-map/index.d.ts
declare module __ReactD3Map {
    export interface IMapProps {
        data?: any;

        center?: number[];

        scaleExtent?: number[];

        scale?: number;

        width?: number;

        height?: number;

        margin?: number;

        min?: number;

        max?: number;

        clip?: boolean;

        bounds?: any[];
    }

    export class Map extends React.Component<IMapProps, {}>{ }

    export class MeshCollection extends React.Component<{}, {}>{ }

    export class MarkerCollection extends React.Component<{}, {}>{ }

    export class PolygonCollection extends React.Component<{}, {}>{ }

    export class LineGroup extends React.Component<{}, {}>{ }

    export class MarkerGroup extends React.Component<{}, {}>{ }


    export interface IPolygonGroupProps {
        
        key?: string;

        data?: any;

        polygonClass?: string;

        popupContent?: any;

        onClick?: any;

        onCloseClick?: any;

        onMouseOver?: any;

        onMouseOut?: any;
    }

    export class PolygonGroup extends React.Component<IPolygonGroupProps, {}>{ }
}

declare module "react-d3-map" {
    export = __ReactD3Map;
}