// Generated by typings
// Source: https://raw.githubusercontent.com/dhsaks/typescript-definitions/66fdaab8fd24902429204d7c269387ca011c1428/react-d3-core/index.d.ts
declare module __ReactD3Core {
    export interface IChartProps {
        title?: string;

        width?: number;

        height?: number;

        margins?: any;

        className?: any;
    }

    export class Chart extends React.Component<IChartProps, {}>{ }

}

declare module "react-d3-core" {
    export = __ReactD3Core;
}