// Generated by typings
// Source: ../Code/typings/react-d3-core/react-d3-core.d.ts
declare module __ReactD3Core {
    export interface IChartProps {
        title?: string;

        width?: number;

        height?: number;

        margins?: any;

        className?: any;
    }

    export class Chart extends React.Component<IChartProps, {}>{ }

}

declare module "react-d3-core" {
    export = __ReactD3Core;
}