// Generated by typings
// Source: https://raw.githubusercontent.com/dhsaks/typescript-definitions/66fdaab8fd24902429204d7c269387ca011c1428/react-d3-basic/index.d.ts
declare module __ReactD3Basic {

    export interface IBasicProps {
        title?: string;

        width?: number;

        height?: number;

        margins?: any;

        data?: any;

        chartSeries?: any;

        x?: any;

        className?: any;
    }

    export class LineChart extends React.Component<IBasicProps, {}>{ }
    
}

declare module "react-d3-basic" {
    export = __ReactD3Basic;
}