// Generated by typings
// Source: https://raw.githubusercontent.com/dhsaks/typescript-definitions/66fdaab8fd24902429204d7c269387ca011c1428/xhr/index.d.ts
declare module Xhr {

    function createXHR(uri: string, options: any, callback: any): void;
}

declare module "xhr" {
    export = Xhr;
}