// Generated by typings
// Source: ../Code/typings/raster-tile-style/raster-tile-style.d.ts


declare module "raster-tile-style" {
    export function rasterTileStyle(tiles: any, tileSize?: number): any;
}