// Generated by typings
// Source: https://raw.githubusercontent.com/dhsaks/typescript-definitions/66fdaab8fd24902429204d7c269387ca011c1428/react-router-active-component/index.d.ts
declare module "react-router-active-component" {
    export default function activeComponent(Component: any, options?: any): any;
}