// Generated by typings
// Source: https://raw.githubusercontent.com/dhsaks/typescript-definitions/e85e2d5ad761066f1cc3d43cbb392af8b562b5c6/react-sparklines/index.d.ts
declare module __ReactSparklines {
    export interface ISparklinesProps {
        data: number[];

        limit?: number;

        width?: number;

        height?: number;

        margin?: number;

        min?: number;

        max?: number;
    }

    export class Sparklines extends React.Component<ISparklinesProps, {}>{ }

    export class SparklinesLine extends React.Component<{ color?: string, style?: any }, {}>{ }

    export class SparklinesReferenceLine extends React.Component<{ type: string }, {}>{ }

    export class SparklinesNormalBand extends React.Component<{}, {}>{ }

    export class SparklinesSpots extends React.Component<{ style?: any }, {}>{ }

    export class SparklinesBars extends React.Component<{}, {}>{ }
}

declare module "react-sparklines" {
    export = __ReactSparklines;
}