/// <reference path="../../../../../../typings/tsd.d.ts" />

export const GET_ACCOUNT_SETTINGS: string = 'GET_ACCOUNT_SETTINGS';
export const GET_ACCOUNT_SETTINGS_RESPONSE: string = 'GET_ACCOUNT_SETTINGS_RESPONSE';
export const SAVE_ACCOUNT_SETTINGS: string = 'SAVE_ACCOUNT_SETTINGS';
export const SAVE_ACCOUNT_SETTINGS_RESPONSE: string = 'SAVE_ACCOUNT_SETTINGS_RESPONSE';
export const GET_USER_SETTINGS: string = 'GET_USER_SETTINGS';
export const GET_USER_SETTINGS_RESPONSE: string = 'GET_USER_SETTINGS_RESPONSE';
export const SAVE_USER_SETTINGS: string = 'SAVE_USER_SETTINGS';
export const SAVE_USER_SETTINGS_RESPONSE: string = 'SAVE_USER_SETTINGS_RESPONSE';
export const SAVE_PASSWORD_SETTINGS: string = 'SAVE_PASSWORD_SETTINGS';
export const SAVE_PASSWORD_SETTINGS_RESPONSE: string = 'SAVE_PASSWORD_SETTINGS_RESPONSE';